name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test imports
        run: |
          python - << 'PY'
          import importlib
          for mod in [
            'pandas','numpy','matplotlib','seaborn','sklearn','statsmodels','plotly','jupyter'
          ]:
              importlib.import_module(mod)
          import src.data_processing
          import src.feature_engineering
          import src.models
          import src.visualization
          print('Smoke imports OK')
          PY

      - name: List project
        run: |
          ls -R
